<a href="https://colab.research.google.com/github/NataliaNietoV/AP0053-20243/blob/main/AP0053-20243/corte%202/virtualidad/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np              #numpy crea el objeto np

In [2]:
list = [25,12,15,66,12,5]
vector = np. array (list)       #la lista se vuelve un arreglo y matriz
print (vector)

[25 12 15 66 12  5]


In [25]:
print (vector + 1)
print (vector * 5 )   #se toma el vector original porque no se actualizo, solo se pide imprimir mas no se le asigna un valor exacto al Vector

[26 13 16 67 13  6]
[125  60  75 330  60  25]


In [8]:
print (np.sum(vector))  #suma todo el vector
print (vector)

135
[25 12 15 66 12  5]


In [9]:
print (np.mean(vector))  #promedio

22.5


In [10]:
print (vector + vector)

[ 50  24  30 132  24  10]


In [16]:
vector2 =np.array([1,2,3,4,5,6])  #debe tener la misma cantidad
print(vector + vector2)

[26 14 18 70 17 11]


In [21]:
#############
#Vectores, listas duplas -----> indices
#Diccionario -----> palabra clave


print (vector[3])
print (vector[1:4])
print (vector)
print (vector[1:])


66
[12 15 66]
[25 12 15 66 12  5]
[12 15 66 12  5]


In [ ]:
########################

In [23]:
#nuevo atributo

vector_zeros =np.zeros(5)
print (vector_zeros)

vector_ones =np.ones(5)
print (vector_ones)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [24]:
vector2 = vector_zeros + 6
print (vector2)
print (vector2 +9)
print (vector2)


[6. 6. 6. 6. 6.]
[15. 15. 15. 15. 15.]
[6. 6. 6. 6. 6.]


In [ ]:
#####################

In [44]:
#MATRIZ PRO MEDIO DE LISTAS

list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(list_of_lists)
print (matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print (matrix[0][0]) # 1,2,3 es 0 e igual con las filas
print (matrix[0])
print (matrix[1])
print (matrix[2])



1
[1 2 3]
[4 5 6]
[7 8 9]


In [33]:
print (np.size(matrix)) #3*3

9


In [47]:
print ('matrix')
print (matrix)
matrix [0][1] = 9
print ("updated matrix")
print (matrix)

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
updated matrix
[[1 9 3]
 [4 5 6]
 [7 8 9]]


In [64]:
##### CODIGO DE ACTIVIDAD ####
list_of_lists = [[0,0,0],[0,0,0],[0,0,0]]
matrix4 = np.array(list_of_lists)
print (matrix4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [67]:
print ('matrix4')
print (matrix4)
matrix4 [1,:] = 4
#matrix4 [1][0] = 4
#matrix4 [1][1] = 4
#matrix4 [1][2] = 4
print ("updated matrix")
print (matrix4)



matrix4
[[0 0 0]
 [0 0 0]
 [0 0 0]]
updated matrix
[[0 0 0]
 [4 4 4]
 [0 0 0]]


In [69]:
print (matrix4)
matrix4 = matrix4 + 5
print (matrix4)

[[0 0 0]
 [4 4 4]
 [0 0 0]]
[[5 5 5]
 [9 9 9]
 [5 5 5]]
